### ISSUE TITLE
shanghaitech only get auc 63.7

### ISSUE THREAD

**Issue by xiadingZ** [fjchange/object_centric_VAD#5] opened 2019-09-12 01:07 UTC
I follow your code and use default parameters, on shanghaitech only get auc 63.7
`dataset = shanghaitech, loss file = /home/dingxia/data/shanghaitech.pkl, auc = 0.6370342604726742`

in order to get your results, how to set parameters?
thanks.

**Comment by fjchange** [comment] 2019-09-12 06:35
Duplicate of #2

**Closed as completed by fjchange** 2019-09-12 06:35 UTC
